stages:
  - build
  - test

build-job:
  stage: build
  image: node:16.10.0
  script:
    - npm install --registry "http://npm.web.dz"
    - npm run build
  artifacts:
    paths:
      - "dist/"

test-job:
  stage: test
  script:
    - npm run test
