include:
  - project: "common-lib/common-ci"
    ref: main
    file: /dingtalk-notice.yml

variables:
  DINGTALK_ACCESS_TOKEN: b4233c5c470159739d6c4995dd0c01e94bf7421cc62560d10c6680e46ce98bd3

stages:
  - build

build-job:
  stage: build
  image: node:16.10.0
  extends: .dingtalk
  script:
    - npm install --registry=http://npm.web.dz
    - npm run build
    - npm run test