import dateFormat from './dateFormat';
import dateRange from './dateRange';
import isArray from './isArray';
import isNumber from './isNumber';
import isObject from './isObject';
import isUndefined from './isUndefined';
import pagination from './pagination';
import parseKeyHeader from './parseKeyHeader';
import toFixed from './toFixed';
import toPercent from './toPercent';
import toThousand from './toThousand';
declare const _default: {
    dateFormat: typeof dateFormat;
    dateRange: typeof dateRange;
    isArray: typeof isArray;
    isNumber: typeof isNumber;
    isObject: typeof isObject;
    isUndefined: typeof isUndefined;
    pagination: typeof pagination;
    parseKeyHeader: typeof parseKeyHeader;
    parseUrl: (address: any, key: any) => any;
    parseUrlByHash: Function;
    parseUrlBySearch: Function;
    toFixed: typeof toFixed;
    toPercent: typeof toPercent;
    toThousand: typeof toThousand;
};
export default _default;
