// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from '/Users/rocsun/Code/dz-library/_o-orange/node_modules/.pnpm/10.10.11.236+4873+dumi@2.1.19_@babel+core@7.22.9_eslint@8.45.0_jest@29.5.0_postcss@8.4.27_pre_i4mkes2vismuycij6ojna4unmy/node_modules/dumi/dist/client/theme-api/index.js';
